[workspace]
resolver = "3"
members = [
    "toni",
    "toni-macros",
    "toni-cli",
    "toni-axum",
    "toni-salvo",
    "toni-poem",
    "toni-rocket",
    "toni-tcp",
    "toni-udp",
    "toni-nats",
    "toni-grpc",
    "toni-build",
    "toni-tungstenite",
    "toni-actix",
    "toni-config",
    "toni-seaorm",
    "toni-prisma",
    "toni-diesel",
    "toni-redis",
    "toni-redis-broadcast",
    "toni-redis-rpc",
    "toni-rabbitmq",
    "toni-mqtt",
    "toni-kafka",
    "toni-sqlx",
    "toni-mongodb",
    "toni-async-graphql",
    "toni-juniper",
    "toni-terminus",
    "integration-tests",
    "examples",
]

[workspace.package]
edition = "2024"
license = "MIT"
repository = "https://github.com/ifeanyi-ugwu/toni-rs"
homepage = "https://github.com/ifeanyi-ugwu/toni-rs"

[workspace.dependencies]
anyhow = "1.0.95"
async-trait = "0.1.86"
bytes = "1"
futures = { version = "0.3", default-features = false, features = ["std"] }
futures-timer = "3"
futures-util = "0.3"
http = "1"
http-body-util = "0.1"
parking_lot = "0.12"
redis = "1"
serde = "1.0.217"
serde_json = "1.0.137"
testcontainers = "0.27.3"
testcontainers-modules = "0.15.0"
tokio = { version = "1.47", default-features = false }
tokio-stream = "0.1"
tokio-tungstenite = "0.28"
tower = { version = "0.5", default-features = false }
tracing = "0.1"
uuid = "1.11"
validator = "0.20.0"
