[workspace]
resolver = "3"
members = [
    "toni",
    "toni-macros",
    "toni-cli",
    "toni-axum",
    "toni-salvo",
    "toni-poem",
    "toni-rocket",
    "toni-tcp",
    "toni-udp",
    "toni-nats",
    "toni-grpc",
    "toni-build",
    "toni-tungstenite",
    "toni-actix",
    "toni-config",
    "toni-seaorm",
    "toni-prisma",
    "toni-diesel",
    "toni-redis",
    "toni-redis-broadcast",
    "toni-redis-rpc",
    "toni-rabbitmq",
    "toni-mqtt",
    "toni-kafka",
    "toni-sqlx",
    "toni-mongodb",
    "toni-async-graphql",
    "toni-juniper",
    "toni-terminus",
    "integration-tests",
    "examples",
]
