use std::sync::Arc;

use async_trait::async_trait;

use crate::context::Metadata;
use crate::enhancer::{ErrorHandler, Guard, Interceptor};
use crate::rpc::{RpcContext, RpcData, RpcHandlerResult};

use super::RpcController;

/// What an RPC controller declares, read once at create. Controller-level entries apply to every
/// handler; each `handlers` entry adds to one pattern. A flat descriptor instead of a dozen
/// accessor methods — the macro builds it, the resolver reads it once.
///
/// Each role arrives two ways. `*_tokens` come from `#[use_guards(MyGuard)]` and resolve against
/// the DI container, so the enhancer may hold injected dependencies. `guards` / `interceptors` /
/// `error_handlers` come from `#[use_guards(MyGuard{})]`, which builds the value at the
/// declaration site and never consults the container. The resolver runs the DI-resolved ones
/// first.
#[derive(Default)]
pub struct RpcEnhancers {
    pub guard_tokens: Vec<String>,
    pub interceptor_tokens: Vec<String>,
    pub error_handler_tokens: Vec<String>,
    pub guards: Vec<Arc<dyn Guard<RpcContext>>>,
    pub interceptors: Vec<Arc<dyn Interceptor<RpcContext, RpcHandlerResult>>>,
    pub error_handlers: Vec<Arc<dyn ErrorHandler<RpcContext, RpcData>>>,
    pub handlers: Vec<RpcHandlerEnhancers>,
}

/// What one handler declares on top of its controller's, keyed by pattern. Same two ways in as
/// [`RpcEnhancers`].
#[derive(Default)]
pub struct RpcHandlerEnhancers {
    pub pattern: String,
    pub guard_tokens: Vec<String>,
    pub interceptor_tokens: Vec<String>,
    pub error_handler_tokens: Vec<String>,
    pub guards: Vec<Arc<dyn Guard<RpcContext>>>,
    pub interceptors: Vec<Arc<dyn Interceptor<RpcContext, RpcHandlerResult>>>,
    pub error_handlers: Vec<Arc<dyn ErrorHandler<RpcContext, RpcData>>>,
}

/// What an RPC controller declares, and where its instances come from.
///
/// The framework reads the declarations at startup — patterns build the dispatch index, enhancer
/// tokens resolve against the role registry — and asks for an instance only once a call is being
/// served. Splitting the two is what lets a controller be built per call: nothing the framework
/// needs before a call arrives is reached through an instance.
///
/// One implementation per `#[patterns]` impl, generated by the macro.
#[async_trait]
pub trait RpcControllerSource: Send + Sync {
    fn token(&self) -> String;

    /// All patterns this controller handles.
    fn patterns(&self) -> Vec<String>;

    /// All enhancer tokens for this controller — controller-level plus per-handler — resolved once
    /// at startup. Default is empty (a controller with no declared enhancers).
    fn enhancers(&self) -> RpcEnhancers {
        RpcEnhancers::default()
    }

    /// What the controller declares for every handler, before any handler adds to it.
    fn metadata(&self) -> Arc<Metadata> {
        Arc::new(Metadata::new())
    }

    /// Per-pattern metadata for handlers that declare their own, already merged over the
    /// controller's. A pattern absent from this list reads [`metadata`](Self::metadata).
    fn handler_metadata(&self) -> Vec<(String, Arc<Metadata>)> {
        Vec::new()
    }

    /// Resolve the controller serving `ctx`.
    ///
    /// A singleton answers with the instance built at startup. A request-scoped one is built
    /// inside `ctx`'s execution, so its request-scoped dependencies resolve against that
    /// execution's cache and are shared with whatever else in the call already asked for them.
    async fn resolve(&self, ctx: &RpcContext) -> Arc<dyn RpcController>;
}
