use std::sync::Arc;

use async_trait::async_trait;

use crate::context::Metadata;
use crate::dispatch::Rpc;
use crate::enhancer::{ErrorHandlerDeclaration, GuardDeclaration, InterceptorDeclaration};
use crate::rpc::RpcContext;

use super::RpcController;

/// What an RPC controller declares, read once at create. Controller-level entries apply to every
/// handler; each `handlers` entry adds to one pattern. A flat descriptor instead of a dozen
/// accessor methods — the macro builds it, the resolver reads it once.
///
/// Each role is one vector in the order written, and the resolver keeps that order. A guard or
/// interceptor entry is a token, a value or a constructor (see
/// [`GuardDeclaration`](crate::enhancer::GuardDeclaration)); an error-handler entry is a token or a
/// value.
#[derive(Default)]
pub struct RpcEnhancers {
    pub guards: Vec<GuardDeclaration<Rpc>>,
    pub interceptors: Vec<InterceptorDeclaration<Rpc>>,
    pub error_handlers: Vec<ErrorHandlerDeclaration<Rpc>>,
    pub handlers: Vec<RpcHandlerEnhancers>,
}

/// What one handler declares on top of its controller's, keyed by pattern. The same spellings as
/// [`RpcEnhancers`].
#[derive(Default)]
pub struct RpcHandlerEnhancers {
    pub pattern: String,
    pub guards: Vec<GuardDeclaration<Rpc>>,
    pub interceptors: Vec<InterceptorDeclaration<Rpc>>,
    pub error_handlers: Vec<ErrorHandlerDeclaration<Rpc>>,
}

/// What an RPC controller declares, and where its instances come from.
///
/// The framework reads the declarations at startup — patterns build the dispatch index, enhancer
/// tokens resolve against the role registry — and asks for an instance only once a call is being
/// served. Splitting the two is what lets a controller be built per call: nothing the framework
/// needs before a call arrives is reached through an instance.
///
/// One implementation per `#[patterns]` impl, generated by the macro.
#[async_trait]
pub trait RpcControllerSource: Send + Sync {
    fn token(&self) -> String;

    /// All patterns this controller handles.
    fn patterns(&self) -> Vec<String>;

    /// All enhancer tokens for this controller — controller-level plus per-handler — resolved once
    /// at startup. Default is empty (a controller with no declared enhancers).
    fn enhancers(&self) -> RpcEnhancers {
        RpcEnhancers::default()
    }

    /// What the controller declares for every handler, before any handler adds to it.
    fn metadata(&self) -> Arc<Metadata> {
        Arc::new(Metadata::new())
    }

    /// Per-pattern metadata for handlers that declare their own, already merged over the
    /// controller's. A pattern absent from this list reads [`metadata`](Self::metadata).
    fn handler_metadata(&self) -> Vec<(String, Arc<Metadata>)> {
        Vec::new()
    }

    /// Resolve the controller serving `ctx`.
    ///
    /// A singleton answers with the instance built at startup. An execution-scoped one is built
    /// inside `ctx`'s execution, so its execution-scoped dependencies resolve against that
    /// execution's cache and are shared with whatever else in the call already asked for them.
    async fn resolve(&self, ctx: &RpcContext) -> Arc<dyn RpcController>;
}
