use std::sync::Arc;

use async_trait::async_trait;

use crate::context::Metadata;
use crate::context::RpcContext;

use super::RpcControllerTrait;

/// The enhancer tokens an RPC controller declares, resolved once at create. Controller-level
/// tokens apply to every handler; each `handlers` entry adds tokens for one pattern. A flat
/// descriptor instead of a dozen accessor methods — the macro builds it, the resolver reads it once.
#[derive(Default)]
pub struct RpcEnhancers {
    pub guard_tokens: Vec<String>,
    pub interceptor_tokens: Vec<String>,
    pub error_handler_tokens: Vec<String>,
    pub handlers: Vec<RpcHandlerEnhancers>,
}

/// Per-handler (per-pattern) enhancer tokens, applied on top of the controller-level ones.
#[derive(Default)]
pub struct RpcHandlerEnhancers {
    pub pattern: String,
    pub guard_tokens: Vec<String>,
    pub interceptor_tokens: Vec<String>,
    pub error_handler_tokens: Vec<String>,
}

/// What an RPC controller declares, and where its instances come from.
///
/// The framework reads the declarations at startup — patterns build the dispatch index, enhancer
/// tokens resolve against the role registry — and asks for an instance only once a call is being
/// served. Splitting the two is what lets a controller be built per call: nothing the framework
/// needs before a call arrives is reached through an instance.
///
/// One implementation per `#[rpc_controller]` struct, generated by the macro.
#[async_trait]
pub trait RpcControllerSource: Send + Sync {
    fn get_token(&self) -> String;

    /// All patterns this controller handles.
    fn get_patterns(&self) -> Vec<String>;

    /// All enhancer tokens for this controller — controller-level plus per-handler — resolved once
    /// at startup. Default is empty (a controller with no declared enhancers).
    fn enhancers(&self) -> RpcEnhancers {
        RpcEnhancers::default()
    }

    /// What the controller declares for every handler, before any handler adds to it.
    fn metadata(&self) -> Arc<Metadata> {
        Arc::new(Metadata::new())
    }

    /// Per-pattern metadata for handlers that declare their own, already merged over the
    /// controller's. A pattern absent from this list reads [`metadata`](Self::metadata).
    fn handler_metadata(&self) -> Vec<(String, Arc<Metadata>)> {
        Vec::new()
    }

    /// The controller serving `ctx`.
    ///
    /// A singleton answers with the instance built at startup. A request-scoped one is built
    /// inside `ctx`'s execution, so its request-scoped dependencies resolve against that
    /// execution's cache and are shared with whatever else in the call already asked for them.
    async fn instance(&self, ctx: &RpcContext) -> Arc<dyn RpcControllerTrait>;
}
