[package]
name = "ulo-graphql-juniper"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Juniper GraphQL integration for the Ulo framework"
keywords = ["graphql", "juniper", "ulo", "web", "framework"]
categories = ["web-programming", "asynchronous"]

[dependencies]
ulo = { path = "../ulo", version = "0.2.0", default-features = false }
ulo-macros = { path = "../ulo-macros", version = "0.2.0" }
juniper = "0.16"
async-trait.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true

[dev-dependencies]
ulo-http-axum = { path = "../ulo-http-axum", version = "0.1.0" }
tokio = { workspace = true, features = ["full"] }
