[package]
name = "toni-prisma"
version = "0.1.0"
edition = "2024"
description = "Prisma integration for the Toni framework"
license = "MIT"
repository = "https://github.com/ifeanyi-ugwu/toni-rs"
homepage = "https://github.com/ifeanyi-ugwu/toni-rs"

[dependencies]
toni = { path = "../toni", default-features = false }
async-trait = "0.1"
